# Top-level defaults
compatibility_date = "2024-07-31"
workers_dev = false

name = "cnhotsearch-api-tools"
main = "worker.js"

#[vars]
#GMYA_KEY = " "
#Finlight_KEY = " "

[assets]
directory = "./static"
